### ISSUE TITLE
Regarding to checkpoints

### ISSUE THREAD

**Issue by MingyuKim87** [1202kbs/DMCMC#1]
When I read README.MD, I need to have checkpoints on score_sde_pytorch and Soft-Truncation.

![image](https://user-images.githubusercontent.com/21028510/193222442-912adbc2-b169-4e78-aff4-b2ca7b3cdeed.png)

There are respectively a lot of checkpoints in two repositories, so that I would like to ask you to choose an appropriate checkpoint to test your basic idea. In other words, could you indicate a specific checkpoint I should use for your code?

For your understanding, I leave screenshots to two repositories. 

1. score_sde_pytorch
![image](https://user-images.githubusercontent.com/21028510/193223172-8460caae-5fcb-472c-bcf0-606af64f27c0.png)

2. Soft-Truncation
![image](https://user-images.githubusercontent.com/21028510/193222840-aa05a9a8-fb86-4ce7-9ee2-635f9cb2e2bb.png)

**Comment by 1202kbs** [comment]
DMCMC is compatible with any VE (or RVE for Soft-Truncation) NCSN. If you are asking which checkpoints we used in our paper, we used

- https://drive.google.com/drive/folders/1Ko7hOCMIM6yFShJCIU4LBsF0sfjWuafa
- https://drive.google.com/drive/folders/1LK2bGXpZBzJKLCcL_NfUKsr8dxT8XVh5

provided by Song et al.

**Comment by MingyuKim87** [comment]
Thanks for your response!
