### ISSUE TITLE
Failed Sampling

### ISSUE THREAD

**Issue by karimul** [1202kbs/DMCMC#2]
Hi Beomsu Kim,

Firstly thanks a lot for your amazing work and contribution to score-matching models.
In recent days, it was particularly interesting to follow your recent paper on Denoising MCMC.

I run your experiment on [Demo.ipynb](https://github.com/1202kbs/DMCMC/blob/main/Demo.ipynb) but the result is not what I expected. All results are noise images and failed to generate realistic images.
![image](https://user-images.githubusercontent.com/5180710/196595801-ad945045-7670-47ca-a7b4-e5278d3c9c3f.png)

Is there any missing step? Particularly on dataset preparation?

**Comment by 1202kbs** [comment]
Hi!

Thank you for your interest in our work :)
Please make sure that you are using the correct checkpoints.

CIFAR10 : https://drive.google.com/drive/folders/1Ko7hOCMIM6yFShJCIU4LBsF0sfjWuafa
CelebA-HQ-256 : https://drive.google.com/drive/folders/1LK2bGXpZBzJKLCcL_NfUKsr8dxT8XVh5

On my machine, the demo code works properly both with and without DMCMC.
If you are using the correct checkpoints, it would be helpful if you show me your code.

![image](https://user-images.githubusercontent.com/14208405/196597777-e3964125-d7c1-4425-9d22-005bf64b9b0a.png)
![image](https://user-images.githubusercontent.com/14208405/196597826-52b72862-5404-40b5-ad1f-aca278b90bb0.png)

**Comment by karimul** [comment]
@1202kbs thank you for your response. it works now
