### ISSUE TITLE
Logs checkpoint for another datasets

### ISSUE THREAD

**Issue by karimul** [1202kbs/DMCMC#3]
logs directory contains checkpoints of the CNN for Cifar10 and CelebaHQ datasets. Can you help me with where I can get checkpoints for another dataset?

**Comment by 1202kbs** [comment]
Hi.

We did not experiment with other datasets, so we do not have checkpoints.

However, I uploaded a demo code for training a noise classifier, so you can experiment with the dataset you have in mind.

https://github.com/1202kbs/DMCMC/blob/main/Noise%20Classifier%20Train%20Demo.ipynb
